version: '3.8'

services:

  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=bank
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Added memory management limits to the command below
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq-broker
      restart: always
      ports:
        - "5672:5672"   # AMQP protocol port
        - "15672:15672" # Management UI port
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:

  redis_data:
  rabbitmq_data: